# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
cmd/eskimo:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 443
    certPath: cmd/eskimo/.testdata/localhost.crt
    keyPath: cmd/eskimo/.testdata/localhost.key
cmd/eskimo-hut:
  host: localhost:1443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 1443
    certPath: cmd/eskimo-hut/.testdata/localhost.crt
    keyPath: cmd/eskimo-hut/.testdata/localhost.key
users: &users
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5433/eskimo
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5433/eskimo
  messageBroker: &usersMessageBroker
    consumerGroup: eskimo-local
    createTopics: true
    urls:
      - localhost:9092
    topics: &usersMessageBrokerTopics
      - name: eskimo-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-device-metadata-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: global-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: contacts-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: mining-sessions-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-pings
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: users-table
      - name: mining-sessions-table
      - name: user-pings
  ip2LocationBinaryPath: ./users/internal/device/metadata/.testdata/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-SAMPLE.BIN
  requiredAppVersion: v0.0.1
  wintr/multimedia/picture:
    urlUpload: https://storage.bunnycdn.com/ice-staging/profile
    urlDownload: https://ice-staging.b-cdn.net/profile
  wintr/analytics/tracking:
    baseUrl: https://api-02.moengage.com
  phoneNumberValidation:
    expirationTime: 3m
    smsTemplate: '{{.code}} is your ice verification code. This code expires in {{.expirationTime}} minutes.'
  emailValidation:
    emailSubject: ICE email verification
    emailBodyHTMLTemplate: |
      <strong>{{.code}}<strong> is your ice verification code. This code expires in <strong>{{.expirationTime}}<strong> minutes.
    fromEmailAddress: no-reply@ice.io
    fromEmailName: ICE
    expirationTime: 3m
  globalAggregationInterval:
    parent: 60m
    child: 1m
users_test:
  <<: *users
  messageBroker:
    <<: *usersMessageBroker
    consumingTopics: *usersMessageBrokerTopics
    consumerGroup: eskimo-local-test
