# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
kyc/social:
  web-scraping-api:
  social-links:
    twitter:
      post-url: /ice_blockchain/status/1712692723336032437
      domains:
        - twitter.com
        - www.twitter.com
        - x.com
        - www.x.com
    facebook:
      domains:
        - www.facebook.com
        - www.m.facebook.com
        - fb.com
        - www.fb.com
