# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
kyc/social:
  web-scraping-api:
  social-links:
    twitter:
      domains:
        - twitter.com
        - x.com
        - t.co
    facebook:
      app-id: test
      app-secret: test
      allow-long-live-tokens: true
